CREATE TABLE IF NOT EXISTS products (
    id varchar(36) PRIMARY KEY NOT NULL, -- IDENTIFIER
    name varchar(255) NOT NULL,
    image_closed varchar(255) NOT NULL,
    image_open varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    story text NOT NULL,
    sourcing_values text NULL DEFAULT NULL,
    ingredients text NULL DEFAULT NULL,
    allergy_info varchar(255) NULL DEFAULT NULL,
    dietary_certifications varchar(50) NULL DEFAULT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone NULL DEFAULT NULL
);

INSERT INTO products(
    id, name, image_closed, image_open,
    description, story, sourcing_values,
    ingredients, allergy_info, dietary_certifications
)
VALUES (
        '2190',
        'Caramel Chocolate Cheesecake',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/caramel-chocolate-cheesecake-truffles-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/caramel-chocolate-cheesecake-truffles-landing-open.png',
        'Caramel Cheesecake Ice Cream with Graham Cracker-Covered Cheesecake Truffles & Chocolate Cookie Swirls',
        'In your cheesecake dreams, is it like you’re spooning through a world of caramel cheesecake ice cream swirled with chocolate cookies in a wonderland of truffles filled with cheesecake? Hello? You can wake up now…',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","sugar","corn syrup","canola oil","cream cheese (pasteurized milk","cream","cheese cultures","salt","carob bean gum)","coconut oil","egg yolks","wheat flour","dried cane syrup","soybean oil","graham flour","eggs","cocoa (processed with alkali)","natural flavors","cocoa","guar gum","butteroil","milk protein concentrate","corn starch","salt","soy lecithin","tapioca starch","pectin","caramelized sugar syrup","baking soda","molasses","honey","carrageenan","vanilla extract"]',
        'contains milk, eggs, wheat and soy',
        'Kosher'
    ),(
        '2189',
        'Chillin'' the Roast™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chillin-the-roast-truffles-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chillin-the-roast-truffles-landing-open.png',
        'Cold Brew Coffee Ice Cream with Chocolate Cookie-Covered Coffee Liqueur Truffles & Fudge Swirls',
        'Our cold brew coffee ice cream not only delivers a chillacious blast of creamy caffeination, it’s also loaded with enough coffee liqueur-filled, cookie crumble-covered truffles to fuel a truffolution.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","coconut oil","egg yolks","butter (cream","salt)","coffee","wheat flour","milk protein concentrate","cocoa (processed with alkali)","soybean oil","guar gum","natural flavor","salt","corn starch","canola oil","rum","soy lecithin","chocolate","baking soda","carrageenan"]',
        'contains milk, eggs, wheat and soy',
        'Kosher'
    ),(
        '2188',
        'Chocolate Shake It™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-shake-it-truffles-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-shake-it-truffles-landing-open.png',
        'Chocolate Malt Milkshake Ice Cream with Chocolate Cookie-Covered Fudge Truffles & Marshmallow Swirls',
        'For those who prefer their ice cream shaken, swirled, and truffled, here’s a chocolate malt milkshake and marshmallow creation we truffled up with euphoric morsels of cookie crumble-covered fudge.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","corn syrup","sugar","coconut oil","egg yolks","cocoa (processed with alkali)","corn starch","wheat flour","barley malt","vanilla extract","soybean oil","eggs","egg whites","milk","guar gum","salt","natural flavors","soy lecithin","canola oil","pectin","baking soda","enzymes","carrageenan"]',
        'contains milk, eggs, wheat and soy',
        'Kosher'
    ),(
        '2139',
        'One Sweet World',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/one-sweet-world-landing-closed.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/one-sweet-world-landing-open.png',
        'Coffee Caramel Ice Creams with Fudge Chunks & Swirls of Marshmallow & Salted Caramel',
        'At Ben & Jerry’s, we believe the world is sweetest when we stand together as one. That’s why we’re asking you to join us in digging deeper to understand issues of racial justice in America. Learn more and take action at benjerry.com/digdeeper',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]', '["cream","skim milk","corn syrup","water","liquid sugar (sugar","water)","sugar","coconut oil","coffee extract","egg yolks","cocoa (processed with alkali)","butter (cream","salt)","egg whites","caramelized sugar syrup","cocoa","sea salt","natural flavor","pectin","carrageenan","guar gum","baking soda","soy lecithin","vanilla extract","salt","milk"]',
        NULL,
        'Kosher'
    ),(
        '641',
        'Americone Dream®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/americone-dream-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/americone-dream-landing-open.png',
        'Vanilla Ice Cream with Fudge-Covered Waffle Cone Pieces & a Caramel Swirl',
        'Founded in fudge-covered waffle cones, this caramel-swirled concoction is the only flavor that gets a s''cream of approval from The Late Show host, Stephen Colbert. What''s sweeter is this flavor supports charitable causes through The Stephen Colbert AmeriCone Dream Fund.',
        NULL,
        NULL,
        NULL,
        NULL
    ),(
        '602',
        'Banana Split',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/banana-split-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/banana-split-landing-open.png',
        'Banana & Strawberry Ice Creams with Walnuts, Fudge Chunks & a Fudge Swirl', 'We turned the classic ice cream parlor sundae you''ve always loved into the at-home flavor creation you''ve always wanted. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","sugar","strawberries","strawberry puree","walnuts","egg yolks","bananas","butter (cream","salt)","coconut oil","cocoa processed with alkali","chocolate liquor","cocoa powder","lemon juice concentrate","natural flavors","guar gum","pectin","milkfat","carrageenan","soy lecithin","vanilla extract"]',
        'may contain other tree nuts',
        'Kosher'
    ),(
        '1381',
        'Blondie Ambition™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/blondie-ambition-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/blondie-ambition-landing-open.png',
        'Buttery Brown Sugar Ice Cream with Blonde Brownies and Butterscotch Toffee Flakes',
        'What makes Ben & Jerry''s so euphoric? Some say it''s the legendary creamy-richness of our flavor creations. Others say it''s the tastebud-boggling combinations of spoon-bending chunks & perfect swirls. We say, "Enjoy!"',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","brown sugar","egg yolks","dried cane syrup","wheat flour","eggs","coconut oil","sugar","butter (cream","salt)","milkfat","soybean oil","corn syrup","salt","guar gum","vanilla extract","corn starch","monocalcium phosphate","sodium acid pyrophosphate","sodium bicarbonate","cocoa","molasses","natural flavor","paprika extract (color)","soy lecithin","carrageenan","lemon juice concentrate"]',
        NULL,
        NULL
    ),(
        '1271',
        'Boom Chocolatta™ Cookie Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/boom-chocolatta-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/boom-chocolatta-landing.png',
        'Mocha & Caramel Ice Creams with Chocolate Cookies, Fudge Flakes & a Chocolate Cookie Core',
        'As you slam dunk your spoon through creamy mocha & caramel to celebrate the epic chocolate cookie-spread core, your technique may not be perfect, but the victory’s perfectly delicious.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","soybean oil","cocoa (processed with alkali)","egg yolks","butter (cream","salt)","coffee extract","corn syrup","rice flour","potato flour","wheat flour","coconut oil","brown sugar","vanilla extract","salt","sodium bicarbonate","natural flavor","cocoa powder","soy lecithin","eggs","chocolate liquor","cocoa butter","milk","whey protein concentrate","guar gum","carrageenan","milkfat"]',
        NULL,
        NULL
    ),(
        '1490',
        'Bourbon Pecan Pie',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/bourbonpeacanpie-pint-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/bourbonpeacanpie-pint-landing-open.png',
        'Buttery Bourbon Ice Cream with Pecans, Shortbread Cookie Pieces & a Whiskey Caramel Swirl',
        'Not long ago we scoop-toured through Texas asking you to elect the best of two Texas-inspired flavors. Thanks to you this bourbon-y whirl of pecans and cookies wrapped in whiskey-kissed caramel is now available Tex-clusively!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","corn syrup","pecans","butter (cream","salt)","wheat flour","egg yolks","sugar","dried cane syrup","whiskey","dry malt extract (barley)","soybean oil","salt","eggs","caramel color","peanut oil","guar gum","baking soda","carrageenan","soy lecithin may contain other tree nuts"]',
        'may contain other tree nuts',
        'Kosher'
    ),(
        '1379',
        'Brewed to Matter™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brewed-to-matter-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brewed-to-matter-landing-open.png',
        'Coffee Ice Cream with Fudge Chunks & a Brownie Batter Swirl',
        'We''re thrilled to add this made-to-matter, brownie batter-swirled batchful of coffee awesomeness to the Ben & Jerry''s family of flavors. It packs a powerful pintful of goodness that''s guaranteed to amaze you with every consciously concocted bite.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["ingredients: cream","skim milk","liquid sugar (sugar","water)","water","sugar","coffee extract","coconut oil","egg yolks","dried cane syrup","cocoa (processed with alkali)","cocoa","butter (cream","salt)","corn syrup","wheat flour","chocolate liquor","canola oil","carrageenan","guar gum","salt","soy lecithin","natural flavor","vanilla extract","milk fat","sodium bicarbonate"]',
        NULL,
        NULL
    ),(
        '1515',
        'Brownie Batter Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brownie-batter-core-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brownie-batter-core-landing.png',
        'Chocolate & Vanilla Ice Creams with Fudge Brownies & a Brownie Batter Core',
        'Spooning your way to brownie nirvana? Smack dab in the middle of this brownie-chunk-filled ice cream there''s a core of unbaked brownie batter calling your name. No, really. We heard it.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Greyston Brownies","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","dried cane syrup","sugar","cocoa (pressed with alkali)","egg yolks","wheat flour","butter (cream","salt)","corn syrup","cocoa","cocoa powder","chocolate liquor","soybean oil","invert sugar","coconut oil","vanilla extract","eggs","canola oil","salt","carrageenan","guar gum","egg whites","natural flavor","soy lecithin","baking soda","malted barley flour"]',
        NULL,
        'Kosher'
    ),(
        '607',
        'Cheesecake Brownie',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cheesecake-brownie-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cheesecake-brownie-landing-open.png',
        'Cheesecake Ice Cream with Cheesecake Brownie Chunks',
        'What do you call a creamy cheesecake ice cream filled with dreamy cheesecake brownies? A surreally good reason to go fetch a spoon. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Greyston Brownies","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","dried cane syrup","corn syrup","cream cheese (pasteurized milk","cream","cheese cultures","salt","carob bean gum)","soybean oil","wheat flour","egg yolks","eggs","cocoa","corn starch","salt","sugar","guar gum","natural flavor","pectin","soy lecithin","vanilla extract","xanthan gum","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '608',
        'Cherry Garcia®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cherry-garcia-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cherry-garcia-landing-open.png',
        'Cherry Ice Cream with Cherries & Fudge Flakes',
        'Our euphorically edible tribute to guitarist Jerry Garcia & Grateful Dead fans everywhere, it’s the first ice cream named for a rock legend and the most famous of our fan-suggested flavors.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","cherries","sugar","egg yolks","coconut oil","cocoa (processed with alkali)","fruit and vegetable concentrates (color)","cocoa powder","guar gum","natural flavors","lemon juice concentrate","carrageenan","milk fat","soy lecithin"]',
        NULL,
        'Kosher'
    ),(
        '610',
        'Chocolate Chip Cookie Dough',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/choc-chip-cookie-dough-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/choc-chip-cookie-dough-landing-open.png',
        'Vanilla Ice Cream with Gobs of Chocolate Chip Cookie Dough',
        'We knew we were onto something big when we made the world’s first batch of Chocolate Chip Cookie Dough ice cream in 1984. Today the flavor still reigns among our all-time most popular concoctions.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","wheat flour","sugar","brown sugar","egg yolks","butter (cream","salt)","expeller pressed soybean oil","eggs","coconut oil","chocolate liquor","vanilla extract","cocoa (processed with alkali)","cocoa powder","salt","molasses","guar gum","cocoa butter","natural flavors","carrageenan","milkfat","soy lecithin"]',
        NULL,
        'Kosher'
    ),(
        '611',
        'Chocolate Fudge Brownie',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-fudge-brownie-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-fudge-brownie-landing-open.png',
        'Chocolate Ice Cream with Fudge Brownies',
        'The fabulously fudgy brownies in this flavor come from New York’s Greyston Bakery, where producing great baked goods is part of their greater-good mission to provide jobs and training to low-income city residents.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Greyston Brownies","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","sugar","cocoa (processed with alkali)","wheat flour","cocoa powder","soybean oil","egg yolks","invert cane sugar","eggs","egg whites","guar gum","salt","carrageenan","vanilla extract","malted barley flour","sodium bicarbonate"]',
        NULL,
        'Kosher'
    ),(
        '614',
        'Chocolate Therapy®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-therapy-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-therapy-landing-open.png',
        'Chocolate Ice Cream with Chocolate Cookies & Swirls of Chocolate Pudding Ice Cream',
        'You know how sometimes you just want to scream? You could just scream, or you could grab a spoon, get a grip, and treat yourself to some primal s''cream therapy of the sublimest chocolate kind. (Euphoria may occur upon tasting.)',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","cocoa (processed with alkali)","wheat flour","sugar","soybean oil","egg yolks","chocolate liquor","brown sugar","cocoa","honey","guar gum","vanilla extract","natural flavors","salt","sodium bicarbonate","cocoa butter","carrageenan","soy lecithin"]',
        NULL,
        'Kosher'
    ),(
        '615',
        'Chubby Hubby®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chubby-hubby-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chubby-hubby-landing-open.png',
        'Vanilla Malt Ice Cream with Peanutty Fudge-Covered Pretzels with Fudge & Peanut Buttery Swirls',
        'Two tricksters convinced a co-worker this flavor really existed (it didn’t), then felt guilty and made him an actual batch packed with pretzels, peanut butter & fudge. He loved it, so did we, and the rest is history. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","peanuts","pretzels (wheat flour","soybean oil","salt","malt)","partially defatted peanut flour","egg yolks","coconut oil","palm kernel oil","wheat flour and malt barley extract","peanut oil","butter (cream","salt)","cocoa (processed with alkali)","vanilla extract","milk","salt","chocolate liquor","guar gum","cocoa","natural flavors","soy lecithin","sodium bicarbonate","carrageenan"]',
        'may contain tree nuts',
        'Kosher'
    ),(
        '616',
        'Chunky Monkey®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chunky-monkey-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chunky-monkey-landing-open.png',
        'Banana Ice Cream with Fudge Chunks & Walnuts',
        'To create a flavor as fun as the name, we monkeyed around with bunches of test batches until we knew we had a winner: the nuttiest chocolatey-chunkiest concoction-gone-bananas you''ll ever go ape for.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","bananas","walnuts","coconut oil","egg yolks","cocoa (processed with alkali)","cocoa powder","lemon juice concentrate","guar gum","natural flavors","milkfat","carrageenan","soy lecithin","vanilla extract"]',
        'may contain other tree nuts',
        'Kosher'
    ),(
        '617',
        'Cinnamon Buns®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cinnamon-bun-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cinnamon-bun-landing-open.png',
        'Caramel Ice Cream with Cinnamon Bun Dough & a Cinnamon Streusel Swirl',
        'Our cool salute to cinnamon buns is so cinnamon-streuseled & dough-loaded, there''s no telling where the cinnamon buns end or the ice cream begins. That''s because it''s one fun flavor all the way through. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","sugar","dried cane syrup","wheat flour","corn syrup","egg yolks","brown sugar","soybean oil","butter (cream","salt)","coconut oil","molasses","salt","cinnamon","soy lecithin","sodium bicarbonate","spice","vanilla extract","guar gum","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '1514',
        'Coconuts for Caramel Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coconuts-for-caramel-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coconuts-for-caramel-landing.png',
        'Caramel & Sweet Cream Coconut Ice Creams with Fudge Flakes & a Caramel Core',
        'How do you spoon your way to euphoria? Do you start with a cool cruise through fudge-kissed coconutty ocean, a quick dip in the caramel sea, or a thrill-dive deep in the well of thick, gooey caramel? Well?',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","coconut","sugar","milk","corn syrup","egg yolks","coconut oil","corn starch","cocoa (processed with alkali)","butter (cream","salt)","milk fat","cocoa powder","pectin","caramelized sugar syrup","guar gum","baking soda","lactase","soy lecithin","vanilla extract","salt","carrageenan","natural flavor"]',
        NULL,
        'Kosher'
    ),(
        '618',
        'Coffee Toffee Bar Crunch',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-toffee-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-toffee-landing-open.png',
        'Coffee Ice Cream with Fudge-Covered Toffee Pieces',
        'Coffee What Bar Crunch? We gave this flavor a new name to go with the new toffee bars we’re using as part of our commitment to source Fairtrade Certified and non-GMO ingredients. We love it and know you will too!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","coconut oil","coffee extract","egg yolks","butter (cream","salt)","almonds","cocoa (processed with alkali)","milk","soy lecithin","cocoa","natural flavor","salt","vanilla extract","vegetable oil (canola","safflower","and/or sunflower oil)","guar gum","carrageenan"]',
        'may contain wheat, peanuts and other tree nuts',
        'Kosher'
    ),(
        '1003',
        'Coffee, Coffee BuzzBuzzBuzz!®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-coffee-buzz-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-coffee-buzz-landing-open.png',
        'Coffee Ice Cream with Espresso Bean Fudge Chunks',
        'Somewhere between the creamy coffee coffee ice cream and the buzzbuzzbuzz of espresso fudge, it hits you: you’re wide awake and in lovelovelove.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","coconut oil","coffee extract","cocoa (processed with alkali)","egg yolks","coffee","guar gum","soy lecithin","vanilla extract","natural flavor","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '1516',
        'Cookies & Cream Cheesecake Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cookies-and-cream-cheesecake-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cookies-and-cream-cheesecake-landing.png',
        'Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core',
        'What''s it called when you find yourself spoon-deep in a rich center of cheesecake in the middle of a cool ice cream universe of chocolate, cheesecake & cookies? A Core encounter of the Ben & Jerriest kind.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","sugar","cocoa (processed with alkali)","butter (cream","salt)","wheat flour","egg yolks","coconut oil","cream cheese (pasteurized milk","cream","cultures","salt","locust bean gum)","milk protein concentrate","brown sugar","modified corn starch","soy lecithin","eggs","carrageenan","salt","natural flavor","guar gum","locust bean gum","baking soda","vanilla extract","xantham gum"]',
        NULL,
        'Kosher'
    ),(
        '623',
        'Everything But The...®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/everything-but-the-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/everything-but-the-landing-open.png',
        'A Collision of Chocolate & Vanilla Ice Creams mixed with Peanut Butter Cups, Fudge-Covered Toffee Pieces, White Chocolatey Chunks & Fudge-Covered Almonds',
        'We''ve combined some of your most favorite Ben & Jerry''s flavors & swirled them into even bigger show-stoppers. Now you can enjoy them in tasty, twisted tandem!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","coconut oil","cocoa (processed with alkali)","egg yolks","peanuts","roasted almonds (almonds","peanut oil)","partially defatted peanut flour","dried cane syrup","butter (cream","salt)","vanilla extract","milk","cocoa","soy lecithin","almonds","salt","guar gum","natural flavors","milk fat","butteroil","vegetable oil (canola","safflower","and/or sunflower oil)","carrageenan","corn maltodextrin"]',
        'may contain wheat and other tree nuts',
        'Kosher'
    ),(
        '624',
        'Half Baked®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/half-baked-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/half-baked-landing-open.png',
        'Chocolate & Vanilla Ice Creams mixed with Gobs of Chocolate Chip Cookie Dough & Fudge Brownies',
        'Ben & Jerry’s is proud to partner with fellow B Corps Greyston and Rhino Bakeries to bring you half baked. The incredible stories behind both the fudge brownies & cookie dough make this a flavor that not only tastes good, but does good.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Greyston Brownies","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","wheat flour","brown sugar","cocoa (processed with alkali)","egg yolks","butter (cream","salt)","cocoa powder","eggs","expeller pressed soybean oil","soybean oil","invert cane sugar","chocolate liquor","vanilla extract","salt","egg whites","guar gum","molasses","cocoa butter","natural flavors","carrageenan","soy lecithin","malted barley flour","sodium bicarbonate"]',
        NULL,
        'Kosher'
    ),(
        '626',
        'Karamel Sutra® Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/karamel-sutra-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/karamel-sutra-landing.png',
        'Chocolate & Caramel Ice Creams with Fudge Chips & a Soft Caramel Core', 'Find your way to the ultimate ice cream experience with our Cores. Whether your primal urges lead you to the center of soft caramel or directly to the fudge chips, you’ll be in total control of your own ice cream destiny.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","water","skim milk","sugar","liquid sugar (sugar","water)","milk","corn syrup","cocoa (processed with alkali)","coconut oil","egg yolks","butter (cream","salt)","milk fat","pectin","cocoa","guar gum","soy lecithin","sodium bicarbonate","vanilla extract","butteroil","carrageenan","salt","natural flavor","lactase"]',
        NULL,
        'Kosher'
    ),(
        '1962',
        'Keep Caramel & Cookie On™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/keep-caramel-and-cookie-on-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/keep-caramel-and-cookie-on-landing-open.png',
        'Caramel Malt Ice Cream with Shortbread Cookies, Fudge Flakes & Caramel Swirls',
        'Our chunk-n-swirl-filled tribute to the famous words of encouragement is a well-caramelled flavor loaded with shortbread cookies galore. In other words, there’s a whole lotta caramel & cookie euphoria aheadia, so keep calm & spoon on!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","corn syrup","sugar","wheat flour","butter (cream","salt)","dried cane syrup","egg yolks","coconut oil","barley malt","cocoa (processed with alkali)","soybean oil","milk","cocoa powder","eggs","salt","baking soda","carrageenan","guar gum","vanilla extract","milk fat","enzymes","soy lecithin","natural flavor"]',
        NULL,
        'Kosher'
    ),(
        '628',
        'Milk & Cookies',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/milk-and-cookies-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/milk-and-cookies-landing-open.png',
        'Vanilla Ice Cream with a Chocolate Cookie Swirl, Chocolate Chip & Chocolate Chocolate Chip Cookies',
        'How do you take classic milk-&-cookie goodness to a whole ''nother level of greatness? We don’t really know what that means, but we know this flavor’s loaded with the most euphoric assortment of cookies we ever dunked, chunked & swirled in our ice cream.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","wheat flour","canola oil","egg yolks","brown sugar","butter (cream","salt)","chocolate liquor","cocoa (processed with alkali)","cocoa","soybean oil","butteroil","eggs","salt","natural flavor","vanilla extract","tapioca starch","honey","guar gum","sodium bicarbonate","cocoa butter","vanilla beans","soy lecithin","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '630',
        'Mint Chocolate Cookie',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/mint-chocolate-cookie-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/mint-chocolate-cookie-landing-open.png',
        'Peppermint Ice Cream with Chocolate Sandwich Cookies',
        'In case you’ve ever wondered what makes this wintry flavor so wicked cool to luge a spoon through: it’s the pepperminty excellence we packed in it, not to mention all those chocolate sandwich cookie moguls. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","wheat flour","egg yolks","palm and palm kernel oil","cocoa (processed with alkali)","salt","sodium bicarbonate","natural flavor","soy lecithin","guar gum","peppermint extract","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '632',
        'New York Super Fudge Chunk®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/new-york-super-fudge-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/new-york-super-fudge-landing-open.png',
        'Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds',
        'In 1985, to make a name for ourselves in New York, we picked a New York kind of name and created a flavor packed with more kinds of chunks than ever before. We figured if the flavor was euphoric in New York, it would be everywhere. It was, and it is.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","cocoa (processed with alkali)","sugar","coconut oil","walnuts","pecans","roasted almonds (almonds","peanut oil)","dried cane syrup","egg yolks","cocoa","milk fat","salt","soy lecithin","vanilla extract","guar gum","butteroil","peanut oil","natural flavors","butter (cream)","carrageenan","corn maltodextrin"]',
        'may contain peanuts and other tree nuts',
        'Kosher'
    ),(
        '1876',
        'Oat of This Swirled™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/oat-of-this-world-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/oat-of-this-world-landing-open.png',
        'Buttery Brown Sugar Ice Cream with Fudge Flakes & Oatmeal Cinnamon Cookie Swirls',
        'When’s the best time to enjoy this blissful mix of brown sugar ice cream with otherworldly swirls of cinnamony oatmeal cookies? Any time between breakfast and bed, from now ‘til whenever.',
        '["Non-GMO","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","canola oil","coconut oil","egg yolks","butter (cream","salt)","cocoa (processed with alkali)","butter oil","wheat flour","oats","brown sugar","cocoa powder","spice","tapioca starch","salt","guar gum","soy lecithin","vanilla extract","baking soda","natural flavor","lemon juice concentrate","carrageenan","milk fat"]',
        NULL,
        'Kosher'
    ),(
        '1272',
        'Peanut Buttah Cookie Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-buttah-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-buttah-landing.png',
        'Peanut Butter Ice Cream with Crunchy Peanut Butter Sugar Bits, Peanut Butter Cookies & a Peanut Butter Cookie Core',
        'For p.b. fans & cookie spread-heads who want it all, here’s a flavor that delivers it, from the creamy to the crunchy to the peanutty core of crushed-cookie stuff that spreads like buttah (and tastes even bettah).',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","peanuts","sugar","soybean oil","egg yolks","wheat flour","rice flour","peanut oil","butter (cream","salt)","coconut oil","potato flour","partially defatted peanut flour","salt","brown sugar","eggs","whey protein concentrate","natural flavor","cocoa butter","peanut flour","soy lecithin","sodium bicarbonate","vanilla extract","guar gum","carrageenan","milk"]',
        'may contain other tree nuts',
        NULL
    ),(
        '635',
        'Peanut Butter Cup',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-cup-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-cup-landing-open.png',
        'Peanut Butter Ice Cream with Peanut Butter Cups',
        'We interrupt our regularly scheduled programming to remind you how much you love ice cream that’s perfectly peanut buttery & peanut butter cuppity at the same time.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","peanuts","sugar","coconut oil","egg yolks","partially defatted peanut flour","peanut oil","milk","cocoa (processed with alkali)","salt","natural flavors","guar gum","cocoa","soy lecithin","carrageenan"]',
        'may contain wheat and tree nuts because the peanut butter cups are made on equipment that also processes wheat and tree nuts',
        'Kosher'
    ),(
        '1119',
        'Peanut Butter Fudge Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-fudge-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-fudge-landing.png',
        'Chocolate & Peanut Butter Ice Creams with Mini Peanut Butter Cups & a Peanut Butter Fudge Core',
        'Find your way to the ultimate ice cream experience with our Cores. Whether your primal urges lead you to the center of peanut butter fudge or directly to the peanut butter cups, you’ll be in total control of your own ice cream destiny.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","peanuts","sugar","coconut oil","cocoa (processed with alkali)","corn syrup","dried cane syrup","egg yolks","cocoa","peanut oil","milk","salt","guar gum","soy lecithin","carrageenan","natural flavor","vanilla extract"]',
        'may contain tree nuts and wheat',
        'Kosher'
    ),(
        '1384',
        'Peanut Butter World®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-world-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/peanut-butter-world-landing-open.png',
        'Milk Chocolate Ice Cream with Peanut Buttery Swirls & Chocolate Cookie Swirls',
        'What makes Ben & Jerry''s so euphoric? Some say it''s the legendary creamy-richness of our flavor creations. Others say it''s the tastebud-boggling combinations of spoon-bending chunks & perfect swirls. We say, "Enjoy!"',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["ingredients: cream","skim milk","liquid sugar (sugar","water)","peanuts","water","sugar","canola oil","cocoa (processed with alkali)","peanut oil","wheat flour","egg yolks","cocoa","butteroil","salt","tapioca starch","guar gum","natural flavor","sodium bicarbonate","soy lecithin","carrageenan"]',
        NULL,
        NULL
    ),(
        '636',
        'Phish Food®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/phish-food-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/phish-food-landing-open.png',
        'Chocolate Ice Cream with Gooey Marshmallow Swirls, Caramel Swirls & Fudge Fish',
        '“Ben was our neighbor through the woods & we''re fond of ice cream. So we teamed up to create Phish Food®. A portion of our royalties from this flavor goes toward environmental efforts in Vermont''s Lake Champlain Watershed. Enjoy!” PHISH',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","corn syrup","water","sugar","cocoa (processed with alkali)","coconut oil","butter (cream","salt)","egg yolks","egg whites","vanilla extract","natural flavors","guar gum","pectin","cocoa","salt","carrageenan","sodium bicarbonate","milk","soy lecithin"]',
        'may contain wheat, peanuts and tree nuts',
        'Kosher'
    ),(
        '637',
        'Pistachio Pistachio',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/pistachio-pistachio-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/pistachio-pistachio-landing-open.png',
        'Pistachio Ice Cream with Lightly Roasted Pistachios',
        'The name alone shows how much we love pistachios. But don''t just take our word for it - let the flavor speak for itself!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","pistachios","egg yolks","sugar","coconut oil","guar gum","salt","natural flavors","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '1098',
        'Pumpkin Cheesecake',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/pumpkin-cheesecake-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/pumpkin-cheesecake-landing-open.png',
        'Pumpkin Cheesecake Ice Cream with a Graham Cracker Swirl',
        'We took the great taste of pumpkin cheesecake & gave it an ice cream upgrade, complete with a complementary graham cracker swirl, so it''s more than just a great flavor: it''s a first-class ticket to pumpkin wonderful.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","sugar","pumpkin puree","soybean oil","egg yolks","corn starch","cream cheese (cultured pasteurized milk and cream","salt","enzymes)","wheat flour","graham flour","salt","butteroil","canola oil","tapioca starch","guar gum","cinnamon","lactic acid","molasses","honey","soy lecithin","sodium bicarbonate","natural flavor","nutmeg","ginger","lemon juice concentrate","cloves","annatto( color)","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '638',
        'Red Velvet Cake',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/red-velvet-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/red-velvet-landing-open.png',
        'Red Velvet Cake Ice Cream with Red Velvet Cake Pieces & a Cream Cheese Frosting Swirl',
        'From the velvety-rich ice cream packed with actual cake pieces to the dreamy cream cheese frosting, there''s a whole lotta Red Velvet Cake revelry aheadia – & it''s best to revel in it before it melts. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","corn syrup","dried cane syrup","cream cheese (pasteurized milk","cream","cheese cultures","salt","carob bean gum","guar gum)","wheat flour","egg yolks","cultured lowfat buttermilk","sugar","coconut oil","butter (cream","salt)","eggs","vegetable and fruit juice concentrates (color)","salt","vanilla extract","guar gum","baking powder (sodium acid pyrophosphate","sodium bicarbonate","corn starch","monocalcium phosphate","calcium sulfate)","natural flavors","buttermilk","rice protein","vinegar","citric acid","corn starch","rice protein concentrate","lactic acid","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '640',
        'S''mores',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/smores-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/smores-landing-open.png',
        'Chocolate Ice Cream with Fudge Chunks, Toasted Marshmallow & Graham Cracker Swirls',
        'Remember when cookouts & campfires kindled your cravings for s''mores, glorious s’mores? We loaded this flavor with all the stuff that makes s’mores so glorious, so you can kindle your cravings whenever, no campfires required.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","sugar","cocoa (processed with alkali)","soybean oil","corn syrup","corn starch","coconut oil","corn syrup solids","wheat flour","graham flour","egg yolks","salt","butteroil","egg whites","canola oil","cocoa powder","guar gum","tapioca starch","molasses","honey","soy lecithin","sodium bicarbonate","vanilla extract","pectin","milkfat","carrageenan","natural flavor"]',
        NULL,
        'Kosher'
    ),(
        '1961',
        'Salted Caramel Almond',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/salted-caramel-almond-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/salted-caramel-almond-landing-open.png',
        'Vanilla Bean Ice Cream with Roasted Almond Slivers, Fudge Flakes & a Salted Caramel Swirl',
        'What makes Ben & Jerry’s so euphoric? Some say it’s the legendary creamy-richness of our flavor creations. Others say it’s the tastebud-boggling combinations of spoon-bending chunks & perfect swirls. We say, “Enjoy!"',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","almonds","milk","egg yolks","coconut oil","corn syrup","cocoa (processed with alkali)","butter (cream","salt)","butteroil","pectin","sea salt","cocoa powder","guar gum","vanilla extract","soy lecithin","baking soda","vanilla beans","milk fat","carrageenan","lactase","natural flavor"]',
        NULL,
        'Kosher'
    ),(
        '1120',
        'Salted Caramel Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/salted-caramel-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/salted-caramel-landing.png',
        'Sweet Cream Ice Cream with Blonde Brownies & a Salted Caramel Core',
        'Find your way to the ultimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you’ll be in total control of your own ice cream destiny.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","milk","brown sugar","wheat flour","egg yolks","sugar","corn syrup","butter (cream","salt)","eggs","soybean oil","butteroil","pectin","sea salt","vanilla extract","baking powder (sodium acid pyrophosphate","sodium bicarbonate","corn starch","monocalcium phosphate)","salt","guar gum","soy lecithin","baking soda","carrageenan","lactase"]',
        NULL,
        'Kosher'
    ),(
        '1273',
        'Spectacular Speculoos™ Cookie Core',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/spectacular-speculoos-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/spectacular-speculoos-landing.png',
        'Dark Caramel & Vanilla Ice Creams with Speculoos Cookies & a Speculoos Cookie Butter Core',
        'To feed your fascination for that spectacular crushed-cookie spread with the funny-looking name, you could tease into the cinnamony-spiced speculoos cookies first, or spoon-dive directly into the cookified core of speculoos cookie butter.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","soybean oil","sugar","egg yolks","wheat flour","rice flour","coconut oil","butter (cream","salt)","corn syrup","brown sugar","potato flour","cocoa butter","molasses","vanilla extract","salt","sodium bicarbonate","spices","whey protein concentrate","honey","soy lecithin","guar gum","caramelized sugar syrup","natural flavor","caramel color","carrageenan","vanilla beans"]',
        NULL,
        'Kosher'
    ),(
        '642',
        'Strawberry Cheesecake',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/strawberry-cheesecake-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/strawberry-cheesecake-landing-open.png',
        'Strawberry Cheesecake Ice Cream with Strawberries & a Thick Graham Cracker Swirl',
        'For strawberry cheesecake lovers who’ve always wanted to have their cheesecake & scoop it, too, we’ve created a flavor jam-packed with strawberry cheesecake-greatness & a fantastic graham-cracker swirl.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","sugar","strawberries","soybean oil","strawberry puree","egg yolks","corn starch","cream cheese (cultured pasteurized milk and cream","salt","enzymes)","wheat flour","graham flour","salt","butteroil","canola oil","guar gum","natural flavors","tapioca starch","molasses","honey","lactic acid","soy lecithin","sodium bicarbonate","lemon juice concentrate","pectin","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '1270',
        'The Tonight Dough®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/tonight-dough-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/tonight-dough-landing-open.png',
        'Caramel & Chocolate Ice Creams with Chocolate Cookie Swirls & Gobs of Chocolate Chip Cookie Dough & Peanut Butter Cookie Dough.',
        'Inspired by the show & host we love staying up late for, here''s a flavor you''ll love spooning into - dedicated to SeriousFun Children''s Network of global camps for children with serious illnesses. Learn more at seriousfunnetwork.org.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","liquid sugar (sugar","water)","skim milk","water","wheat flour","sugar","canola oil","brown sugar","cocoa (processed with alkali)","egg yolks","peanut butter (peanuts)","corn syrup","eggs","butter (cream","salt)","cocoa","expeller pressed soybean oil","butteroil","salt","chocolate liquor","tapioca starch","guar gum","natural flavor","vanilla extract","molasses","sodium bicarbonate","cocoa butter","carrageenan","soy lecithin"]',
        NULL, NULL
    ),(
        '643',
        'Triple Caramel Chunk®',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/triple-caramel-chunk-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/triple-caramel-chunk-landing-open.png',
        'Caramel Ice Cream with a Swirl of Caramel & Fudge-Covered Caramel Chunks',
        'Caramel lovers won’t want to miss a single moment of this must-eat caramel thrillogy, starring creamy caramel ice cream, gooey caramel swirls, and chewy caramel chunks. They probably won’t want it to end, either. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]', '["cream","skim milk","water","liquid sugar (sugar","water)","corn syrup","sugar","egg yolks","coconut oil","butter (cream","salt)","milk","cocoa (processed with alkali)","salt","guar gum","carrageenan","vanilla extract","sodium bicarbonate","cocoa","soy lecithin","natural flavor"]',
        'may contain peanuts and tree nuts because the fudge covered caramel chunks are made on equipment that also processes these nuts',
        'Kosher'
    ),(
        '1877',
        'Truffle Kerfuffle™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/truffle-kerfuffle-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/truffle-kerfuffle-landing-open.png',
        'Vanilla Ice Cream with Roasted Pecans, Fudge Chips & a Salted Chocolate Ganache Swirl',
        'From the rich collision of sweet vanilla & salty chocolate, to the chunky ruckus of pecans & fudge, it’s the truffle kerfuffle of the century, & you’ve got nothing to lose but your spoon.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","pecans","coconut oil","cocoa (processed with alkali)","egg yolks","corn syrup","butter (cream","salt)","cocoa","chocolate liquor","peanut oil","salt","natural flavors","sea salt","guar gum","vanilla extract","milk fat","vanilla beans","carrageenan","soy lecithin"]',
        'may contain other tree nuts',
        'Kosher'
    ),(
        '1878',
        'Urban Bourbon™',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/urban-bourbon-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/urban-bourbon-landing-open.png',
        'Burnt Caramel Ice Cream with Almonds, Fudge Flakes & Bourbon Caramel Swirls',
        'Want to enjoy a night on the town without leaving the house? Treat yourself to a caramel concoction that’s bold, toasty and bourbon-swirled, with lots of nuts and fudge for fun.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","water","liquid sugar (sugar","water)","corn syrup","sugar","almonds","coconut oil","egg yolks","cocoa (processed with alkali)","butter (cream","salt)","whiskey","caramelized sugar syrup","cocoa powder","dry malt extract (barley)","guar gum","salt","carrageenan","baking soda","milk fat","soy lecithin","vanilla extract","natural flavor"]',
        NULL,
        'Kosher'
    ),(
        '644',
        'Vanilla',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-landing-open.png',
        'Vanilla Ice Cream',
        'When you dig into this pint, you’ll find a rich, creamy Vanilla that’s more vanilla-tasting than any Vanilla you’ve ever tasted.',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","egg yolks","sugar","guar gum","vanilla extract","vanilla beans","carrageenan"]',
        NULL,
        'Kosher'
    ),(
        '645',
        'Vanilla Caramel Fudge',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-caramel-fudge-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-caramel-fudge-landing-open.png',
        'Vanilla Ice Cream with Swirls of Caramel & Fudge',
        'If you’ve been looking for reasons to try something chunkless, this container holds a Vanilla-rich, fudge-luscious & caramel-gooey pintful of them. Enjoy!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","corn syrup","sugar","butter (cream","salt)","egg yolks","vanilla extract","cocoa (processed with alkali)","chocolate liquor","salt","carrageenan","guar gum","sodium bicarbonate"]',
        NULL,
        'Kosher'
    ),(
        '646',
        'Vanilla Toffee Bar Crunch',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-toffee-landing.png',
        '/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/vanilla-toffee-landing-open.png',
        'Vanilla Ice Cream with Fudge-Covered Toffee Pieces',
        'Vanilla What Bar Crunch? We gave this flavor a new name to go with the new toffee bars we’re using as part of our commitment to source Fairtrade Certified and non-GMO ingredients. We love it and know you will too!',
        '["Non-GMO","Cage-Free Eggs","Fairtrade","Responsibly Sourced Packaging","Caring Dairy"]',
        '["cream","skim milk","liquid sugar (sugar","water)","water","sugar","coconut oil","egg yolks","butter (cream","salt)","vanilla extract","almonds","cocoa (processed with alkali)","milk","soy lecithin","cocoa","natural flavor","salt","vegetable oil (canola","safflower","and/or sunflower oil)","guar gum","carrageenan"]',
        'may contain wheat, peanuts and other tree nuts',
        'Kosher'
    );